### ISSUE TITLE
我来提第一个issues吧

### ISSUE THREAD

**Issue by tong822218** [0604hx/grid-form#1]
感觉写的很好，会一直更新维护吗？

**Comment by 0604hx** [comment]
> 感觉写的很好，会一直更新维护吗？

激动，非常感谢您的第一个 issues 哈哈。这个项目会一直维护，有什么新想法会不断增加上去 💪

**Comment by 0604hx** [comment]
感谢支持，最新发布的`0.1.0`版本增加嵌套表单、按钮（可自定义脚本）、图片等组件
